# This file was autogenerated. DO NOT EDIT!
{
  version = "v2.7.6";
  cfVersion = "v0.0.0-20240405130444-44030f9306f4";
  vendorHash = "sha256-P5j2Lo5QZdxFyHdfUIozwlxDZ4PiwT/fOwn7f4MZPFQ=";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.7.6";
    hash = "sha256-uY6MU8iXfGK6+HP2Lc+3iPE5wY35NbGp8pMZWpNVPSg=";
  };
}
