# This file was autogenerated. DO NOT EDIT!
{
  version = "v2.8.1";
  cfVersion = "v0.0.0-20240405130444-44030f9306f4";
  vendorHash = "sha256-XA2mz97EQ+mlGWrSTzz7/n1HxPFOxj2DCCzQV/Myjac=";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.8.1";
    hash = "sha256-fgrQ0LJpzFiYkKUFnkOlvk83dYipovpRUDzp0ZnA5ng=";
  };
}
