#!/usr/bin/env -S nix develop .#update -c bash

ROOT_DIR="$(pwd)"

git_push() {
    (
        cd "$ROOT_DIR" || return
        git config --global user.name 'Updater'
        git config --global user.email 'robot@nowhere.invalid'
        git remote update

        alejandra .
        git add .

        git commit -m "$1"
        git push
    )
}

updateFlakeLock() {
    nix flake update
    git_push "chore: update flake.lock"
}

updateInfo() {
    version=$(sed -n 's#.*github.com/caddyserver/caddy/v2 \(.*\)#\1#p' "$ROOT_DIR/src/go.mod")
    cfVersion=$(sed -n 's#.*github.com/caddy-dns/cloudflare \(.*\)#\1#p' "$ROOT_DIR/src/go.mod")
    dist_hash=$(nix-prefetch-github caddyserver dist --rev "$version" | jq -r .hash)

    {
        echo '# This file was autogenerated. DO NOT EDIT!'
        echo '{'
        echo "  version = \"$version\";"
        echo "  cfVersion = \"$cfVersion\";"
        echo "  vendorHash = \"$1\";"
        echo "  dist = {"
        echo "    owner = \"caddyserver\";"
        echo "    repo = \"dist\";"
        echo "    rev = \"$version\";"
        echo "    hash = \"$dist_hash\";"
        echo "  };"
        echo '}'
    } >"$ROOT_DIR/pkgs/info.nix"
}

updateGoSources() {
    current_version=$(nix eval --json --file ./pkgs/info.nix | jq -r .version)
    current_cf=$(nix eval --json --file ./pkgs/info.nix | jq -r .cfVersion)

    cd ./src || return
    old_hash="$(sha256sum ./go.sum)"

    rm go*
    go mod init caddy
    go mod tidy

    new_hash="$(sha256sum ./go.sum)"

    if [ "$old_hash" != "$new_hash" ]; then
        updateInfo ""
        new_vendor_hash="$(nix build ../.# |& sed -n 's/.*got: *//p')"
        updateInfo "$new_vendor_hash"

        new_version=$(nix eval --json --file ../pkgs/info.nix | jq -r .version)
        new_cf=$(nix eval --json --file ../pkgs/info.nix | jq -r .cfVersion)

        commit_msg="ci: "

        if [[ "$current_version" != "$new_version" ]]; then
            commit_msg+="caddy $current_version -> $new_version"

        elif [[ "$current_cf" != "$new_cf" ]]; then
            commit_msg+="cloudflare-plugin $current_cf -> $new_cf"

        else
            commit_msg+="bump deps"
        fi

        git_push "$commit_msg"
    fi
}

updateFlakeLock
updateGoSources
