# This file was autogenerated. DO NOT EDIT!
{
  version = "2.8.4";
  cfVersion = "0.0.0+89f16b99c18e";
  vendorHash = "sha256-dEuxEG6mW2V7iuSXvziR82bmF+Hwe6ePCfdNj5t3t4c=";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.8.4";
    hash = "sha256-O4s7PhSUTXoNEIi+zYASx8AgClMC5rs7se863G6w+l0=";
  };
}
