# This file was autogenerated. DO NOT EDIT!
{
  version = "2.8.4";
  cfVersion = "0.0.0+d11ac0bfeab7";
  vendorHash = "sha256-AzrRZi1dGZLVx+1vW+jCNgwq/1YFQU+OaNlMjUj2bI0=";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.8.4";
    hash = "sha256-O4s7PhSUTXoNEIi+zYASx8AgClMC5rs7se863G6w+l0=";
  };
}
