# This file was autogenerated. DO NOT EDIT!
{
  version = "2.8.4";
  cfVersion = "0.0.0+5ccabecdc6aa";
  vendorHash = "sha256-+iQy0/3FFraPoDfJSy+Z52odCdSB2G/Ald0LqTXHZGc=";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.8.4";
    hash = "sha256-O4s7PhSUTXoNEIi+zYASx8AgClMC5rs7se863G6w+l0=";
  };
}
